### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by lvp11** [BySpectro/kiri_notifications#1]
Hey!

It`s not working, i guess.
I need kiri_utils to make it working?
I'm using the exports but nothing shows up on the screen.

Example:
`exports.kiri_notifications:KiriShowProgressBar(500, "Teste")`

Any ideas?

**Comment by BySpectro** [comment]
> Hey!
> 
> It`s not working, i guess.
> I need kiri_utils to make it working?
> I'm using the exports but nothing shows up on the screen.
> 
> Example:
> `exports.kiri_notifications:KiriShowProgressBar(500, "Teste")`
> 
> Any ideas?

**Comment by BySpectro** [comment]
Hey!
add this.

**Comment by BySpectro** [comment]
Hey!
Add this.
[kiri_utils.zip](https://github.com/BySpectro/kiri_notifications/files/3510431/kiri_utils.zip)
